services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://kubouser:kubopass@db:5432/kubodb?schema=public
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kubo-network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=kubouser
      - POSTGRES_PASSWORD=kubopass
      - POSTGRES_DB=kubodb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U kubouser -d kubodb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kubo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    labels:
      - "coolify.fqdn=https://kubo.casabero.com"
      - "coolify.port=80"
    depends_on:
      - backend
    networks:
      - kubo-network

networks:
  kubo-network:
    driver: bridge

volumes:
  postgres_data:
